server:
  port:8080

logging:
  config: classpath:logback-dev.xml

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nifi_backend_db
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: /home/dongpil/uploads

nifi:
  base-url: http://192.1.1.92:31147/nifi-api
