version: "3"
services:
  database:
    container_name: nifi_backend_db
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "nifi_backend_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"